var plants = [
    {
        name: "Snake Plant Laurentii", 
        plantImage: "https://i.imgur.com/jian5xm.png",
        scientificName: "Sansevieria trifasciata 'Laurentii'",
        price: 12, 
        quantityAvail: 10,
        description: "Sansevieria trifasciata 'Laurentii' is a cultivar of snake plant with yellow variegated edges. Snake plants are tropical plants that are also succulents. Often positioned as low light plants, they are actually medium to bright light plants that tolerate, but not thrive in low light. Like other succulent plants, they have a modified form of photosynthesis, where in order to preserve water, the plant opens its pores exclusively at night. However, since photosynthesis only happens with daylight, the plant stores carbon dioxide acquired at night for use during the day, and releases oxygen (one of the end products of photosynthesis) at night when the pores open. This helps it to maximize efficiency in cleaning the air, as found in study conducted by NASA.",
        sunlight: 'parsed',
        maintenance: 'low',
        size: 'small',
        moisture: 'medium',
        humidity: 'normal',
        expertiseLevel: 'beginner',
        plantOrigins: 'Southern and Central Africa'
    },
    {
        name: "Aloe Hedgehog", 
        plantImage: "https://i.imgur.com/TnohziJ.png",
        scientificName: "Aloe humilis",
        price: 10, 
        quantityAvail: 10,
        description: "There are many species of aloe, but Aloe humilis is grown for beauty rather than for medicine, like its cousin, Aloe vera. This blue-green aloe flowers once a year with show-stopping fire-red and yellow flowers on tall spikes. Like other aloes, they generate special protein-sugars and sugar-alcohols that take the place of water when the plant dries out, which prevents oxidative damage by stabilizing the plant's DNA and proteins. Although this plant could be used on the skin, it is neither juicy enough, nor grows as quickly as A. vera, so it's best to keep this plant as-is.",
        sunlight: 'direct',
        maintenance: 'low',
        size: 'small',
        moisture: 'low',
        humidity: 'dry',
        expertiseLevel: 'beginner',
        plantOrigins: 'Endemic to South Africa'
    },
    {
        name: "ZZ Plant", 
        plantImage: "https://i.imgur.com/3Iw0NpQ.png",
        scientificName: "Zamioculcas zamiifolia",
        price: 19, 
        quantityAvail: 10,
        description: "Zamioculcas zamiifolia, affectionately called the ZZ plant or Zanzibar Gem, is a tropical plant in the aroid family, Araceae. You might spot large potato-like rhizomes under the surface of its potting mix. Having evolved in drier conditions than most other aroids, these plants have evolved rhizomes that store water to help the ZZ plant survive drought in its natural environment. The rhizomes are actually underground stems, and what you see above ground are the stems' leaves. Using these underground rhizomes, the plant slowly creeps over time to new locations, spawning new aboveground leaves along the way.",
        sunlight: 'parsed',
        maintenance: 'low',
        size: 'medium',
        moisture: 'medium',
        humidity: 'normal',
        expertiseLevel: 'beginner',
        plantOrigins: 'Zanzibar, Kenya, and Eastern Africa'
    },
    {
        name: "Pothos Neon", 
        plantImage: "https://i.imgur.com/Y7VTKbY.png",
        scientificName: "Epipremnum aureum",
        price: 8, 
        quantityAvail: 10,
        description: "Epipremnum aureum, or Pothos, is a tropical aroid vine in the family Araceae. Like other closely-related aroids, this plant's leaves will change in shape with age (similar to a Monstera). The leaves can be found in the wild sprawled out along the ground and climbing up trees. Considered to be in the monstera subfamily Monsteroideae, these plants can truly grow monsterous! In mature plants, the leaves can grow to be longer than 3 feet long. Pothos have the ability to spontaneously generate variegation, which has led to several cultivars of variegation and color– marble, neon, and classic jade.",
        sunlight: 'none',
        maintenance: 'medium',
        size: 'small',
        moisture: 'high',
        humidity: 'normal',
        expertiseLevel: 'beginner',
        plantOrigins: 'French Polynesia'
    },
    {
        name: "Calathea Rattlesnake", 
        plantImage: "https://i.imgur.com/S3sqnsZ.png",
        scientificName: "Calathea lancifolia",
        price: 12, 
        quantityAvail: 10,
        description: "Calathea lancifolia, the Rattlesnake Calathea, is a colorful member of the prayer plant family, Marantaceae. Calatheas are often called 'prayer plants' because of their unique leaf movements –– they raise and lower their leaves from day to night as a part of their circadian rhythm. This phenomenon is called nyctinasty. Plant movements are controlled by a flux of water pressure in the pulvini - nodes at the base of the leaves. Scientists theorize that these movements are meant to follow the sun and catch as much light as possible –– an essential trait for a forest-floor-dwelling plant!",
        sunlight: 'parsed',
        maintenance: 'medium',
        size: 'small',
        moisture: 'high',
        humidity: 'humid',
        expertiseLevel: 'intermediate',
        plantOrigins: 'Brazil'
    },
    {
        name: "Peperomia Green", 
        plantImage: "https://i.imgur.com/UYYucbU.png",
        scientificName: "Peperomia obtusifolia",
        price: 8, 
        quantityAvail: 10,
        description: "Peperomia obtusifolia is a species of Peperomia, named obtusifolia, meaning blunt-leaved. Some leaves may be more obtuse than others, and some might be split, which is natural variation. Peperomias are related to black peppercorns, and are in the family Piperaceae. Like other plants in the family, the flower stalk is cream colored, and the tiny flowers lack a perianth (petals or sepals). This peperomia is easily propagated via leaf-cuttings, and is able to regenerate after completely dying back to the stem.",
        sunlight: 'parsed',
        maintenance: 'medium',
        size: 'small',
        moisture: 'high',
        humidity: 'normal',
        expertiseLevel: 'intermediate',
        plantOrigins: 'The tropical Americas including the Caribbean'
    },
    {
        name: "Norfolk Island Pine", 
        plantImage: "https://i.imgur.com/5It73Kl.png",
        scientificName: "Araucaria heterophylla",
        price: 19, 
        quantityAvail: 10,
        description: "Araucaria heterophylla, or the Norfolk Island Pine, is descended from an ancient lineage of cone-bearing trees, existing long before flowers evolved. These trees would have been lost to history during the Cretaceous Extinction Event, if it were not for a few members of the species surviving on Norfolk Island, in the South Pacific. Although most cone-bearing trees like pines are better suited for cold conditions, the Norfolk Island Pine is uniquely tropical. These trees can survive the salt sprays from the ocean and the heat of the tropical day - most other plants cannot.",
        sunlight: 'direct',
        maintenance: 'medium',
        size: 'large',
        moisture: 'high',
        humidity: 'normal',
        expertiseLevel: 'intermediate',
        plantOrigins: 'New Caledonia and Norfolk Island'
    },
    {
        name: "Xerographica Air Plant", 
        plantImage: "https://i.imgur.com/2uBK9OZ.png",
        scientificName: "Tillandsia xerographica",
        price: 20, 
        quantityAvail: 10,
        description: "Tillandsia xerographica is a dry-forest epiphyte in the bromeliad family, Bromeliaceae. As an epiphyte, it grows on top of tree branches and pulls all the water it needs from the intense morning fogs of its native habitat. These fogs naturally dry up by midday, and the plant collects nutrients from the desert dust that blows around to sustain itself. Like other bromeliads, it grows from a central rosette, radiating out its leaves. This growth is slow, taking years to reach its maximum 3 feet in diameter. Tillandsia are also monocarpic, meaning that once it flowers it dies, but not before producing pups (baby air plants) at their base.",
        sunlight: 'direct',
        maintenance: 'high',
        size: 'small',
        moisture: 'high',
        humidity: 'normal',
        expertiseLevel: 'expert',
        plantOrigins: 'Tropical Americas'
    },
    {
        name: "Mini Marimo ‘Moss’ Ball", 
        plantImage: "https://i.imgur.com/3jGPVh7.png",
        scientificName: "Aegagropila linnaei",
        price: 5, 
        quantityAvail: 10,
        description: "The name of Marimo (毬藻) originated from Japanese botanist Tatsuhiko Kawakami (毬 ‘mari’ = ball and 藻 ‘mo’ = generic term for aquatic plants) who first described them growing in lakes on the island of Hokkaido. The Marimo’s shape is the result of freshwater lake motion. Marimo grow quite slowly, at only a few millimeters a year. Marimo moss, as it’s known, is not actually moss at all. Aegagropila linnaei is a freshwater, fuzzy, filamentous green algal colony. As the colony grows, the inner cells go dormant. If the ball is ever split apart, those cells can reactivate to repair the colony - even under artificial light!",
        sunlight: 'none',
        maintenance: 'medium',
        size: 'small',
        moisture: 'high',
        humidity: 'humid',
        expertiseLevel: 'beginner',
        plantOrigins: 'Northern Hemisphere Cold, Alkaline Lakes- Iceland, Japan, Scotland, Estonia, Australia'
    },
    {
        name: "Starfish Snake Plant", 
        plantImage: "https://i.imgur.com/vLdjVDu.png",
        scientificName: "Sansevieria cylindrica",
        price: 12, 
        quantityAvail: 10,
        description: "Sansevieria cylindrica is a species of snake plant that has cylindrical, fleshy leaves. Starfish Snake Plant is a variety that grows in a fan, or specifically a radially distichous form. Long grown as low light plants, they are actually medium to bright light plants that tolerate, but do not thrive in, low light. Like other succulent plants, they have a modified form of photosynthesis called CAM photosynthesis, where in order to save water, the plant opens its pores at night. However, since photosynthesis only happens with daylight, the plant stores carbon dioxide acquired at night for use during the day, and releases oxygen (one of the end products of photosynthesis) at night when the pores reopen. This helps it to maximize efficiency in cleaning the air, as found in a NASA study.",
        sunlight: 'none',
        maintenance: 'low',
        size: 'small',
        moisture: 'medium',
        humidity: 'normal',
        expertiseLevel: 'beginner',
        plantOrigins: 'Angola, Zambia, Zimbabwe'
    },
    {
        name: "Aloe Vera", 
        plantImage: "https://i.imgur.com/DkuojiQ.png",
        scientificName: "Aloe vera",
        price: 10, 
        quantityAvail: 10,
        description: "Of the 300-plus species of Aloe, only the Aloe vera species is used for medicinal purposes. The ancient Egyptians and Mesopotamians have kept extensive records of Aloe's use –– it's even referenced in the Book of the Dead as part of the skin-preservation process during mummification! Its secret? The Aloe generates special protein-sugars and sugar-alcohols that take the place of water when the plant dries out, which prevents oxidative damage by stabilizing the plant's DNA and proteins. The sugar-alcohol glycerol from Aloe is used in many beauty products.",
        sunlight: 'direct',
        maintenance: 'medium',
        size: 'small',
        moisture: 'low',
        humidity: 'dry',
        expertiseLevel: 'intermediate',
        plantOrigins: 'North Africa and the Middle East'
    },
    {
        name: "Jade", 
        plantImage: "https://i.imgur.com/tjlmE5S.png",
        scientificName: "Crassula ovata",
        price: 19, 
        quantityAvail: 10,
        description: "Crassula ovata is known by many names, including: Jade Plant, Friendship Plant, Money Plant, and many more. This plant is actually an early dicot flowering plant, and belongs to the stonecrop family, Crassulaceae. Like other stone crops such as Echeveria, Sedum, and Cotyledon, these plants can be propagated from virtually any part of the plant, including the leaves, stems, and seeds! In some species, they will even produce roots on branches in anticipation of a strong wind blowing that part of the plant off. With roots already grown, the broken piece tumbles along until it re-roots, growing into a new plant. These plants are so prolific that they are often considered to be weedy pests in greenhouses.",
        sunlight: 'direct',
        maintenance: 'low',
        size: 'small',
        moisture: 'low',
        humidity: 'normal',
        expertiseLevel: 'beginner',
        plantOrigins: 'Southern Africa'
    },
    {
        name: "Haworthia Zebra", 
        plantImage: "https://i.imgur.com/BqfysAH.png",
        scientificName: "Haworthia",
        price: 13, 
        quantityAvail: 10,
        description: "Haworthia are hardy succulents that are so closely related to gasterias and aloes that they can cross breed with each other freely to form hybrids. With such a variable morphology and crossing habits, there is much debate to the placement of these plants within the family, Asphodelaceae (subfamily Alooideae). Due to so many naturally-occurring hybrids, identification and definition of any species is difficult. Some hybrids have accidentally been named as separate species, which adds to the confusion. Some scientists even think that they should all be separate species under one genus.",
        sunlight: 'direct',
        maintenance: 'low',
        size: 'small',
        moisture: 'low',
        humidity: 'normal',
        expertiseLevel: 'beginner',
        plantOrigins: 'Southern Africa'
    },
    {
        name: "Panda Plant", 
        plantImage: "https://i.imgur.com/l1Gfu4I.png",
        scientificName: "Kalanchoe tomentosa",
        price: 14, 
        quantityAvail: 10,
        description: "Kalanchoe tomentosa, also known as Panda Plant, is a species of Kalanchoe that is extra fuzzy to aid in its succulent abilities. The fuzz acts as a sun blocker, to help dim the amount of sunlight that hits the plant. This helps it to cool down and prevent cellular damage from overexposure from the sun. The fuzz also blocks the wind from blowing against the plant directly, preventing water loss. Its hairs also help the plant blend into its environment to prevent death by herbivory (being eaten by animals!). The hairs make dark brown stripes which grow in an irregular pattern to further camouflage the plant from its herbivore predators.",
        sunlight: 'direct',
        maintenance: 'low',
        size: 'small',
        moisture: 'low',
        humidity: 'normal',
        expertiseLevel: 'beginner',
        plantOrigins: 'Madagascar'
    },
    {
        name: "Rubber Tree", 
        plantImage: "https://i.imgur.com/HRPp63D.png",
        scientificName: "Ficus elastica",
        price: 8, 
        quantityAvail: 10,
        description: "Ficus elastica is a species of evergreen tropical tree belonging to the fig family, Moraceae. Due to the amount of isoprene it produces, its latex sap was once used to make rubber before synthetics and other natural alternatives became available. In addition to being useful for rubber, in India, the Ficus elastica roots are used to make living bridges! A rotting tree trunk is put across a river, and the roots are guided along the trunk, grow to the other side, and thicken, to complete the bridge. The bridge, being alive and flexible, resists wind and flooding.",
        sunlight: 'parsed',
        maintenance: 'medium',
        size: 'medium',
        moisture: 'high',
        humidity: 'normal',
        expertiseLevel: 'intermediate',
        plantOrigins: 'Indochina, through Southeast Asia to Indonesia'
    },
    {
        name: "Parlor Palm", 
        plantImage: "https://i.imgur.com/9Vrl5fo.png",
        scientificName: "Chamaedorea elegans",
        price: 12, 
        quantityAvail: 10,
        description: "Chamaedorea elegans, also known as the Neanthe Bella Parlor Palm, is one of our favorite true palms. With the right care and many, many repottings, the Parlor Palm can grow to well over six feet tall. But do not repot more than once a year, as their roots like to relax. Although in the same family as coconuts and dates, which produce edible fruit from flowers at the top of the plant, this plant produces inedible fruit from flowers at the base of the plant. Cultivated since the Victorian era, this species of palm is prized for its resilience to indoor conditions and reliable habit.",
        sunlight: 'parsed',
        maintenance: 'medium',
        size: 'large',
        moisture: 'high',
        humidity: 'humid',
        expertiseLevel: 'beginner',
        plantOrigins: 'Mexico and Guatemala'
    },
    {
        name: "Dino Plant", 
        plantImage: "https://i.imgur.com/eo7XVPf.png",
        scientificName: "Selaginella lepidophylla",
        price: 18, 
        quantityAvail: 10,
        description: "Selaginella lepidophylla, or Dino Plant, is an ancient plant that evolved 400MYA alongside ferns. It belongs to the 'club mosses' group- but are neither mosses, nor belong to any clubs. This particular Selaginella survived the changing climates of North America by adapting in a rather clever way. They have the ability to completely dry out, and then in the event of rain, can completely revive. They do this by preserving all of their DNA and proteins with special protective proteins and sugar-alcohols. The proteins and sugar alcohols produced by this plant are under research for use in medicine preservation and stabilization (such as insulin-preservation).",
        sunlight: 'direct',
        maintenance: 'high',
        size: 'medium',
        moisture: 'high',
        humidity: 'humid',
        expertiseLevel: 'expert',
        plantOrigins: 'Chihuahuan Desert, North America'
    },
    {
        name: "Staghorn Fern", 
        plantImage: "https://i.imgur.com/2qRM2P6.png",
        scientificName: "Platycerium spp.",
        price: 9, 
        quantityAvail: 10,
        description: "Platycerium spp., or Staghorn Ferns, are different from other ferns in that they are epiphytes, living on trees instead of in the soil, and they are high-light lovers. They have pronounced sporophytes (the stags) and pronounced gametophytes (the shields), and both are separate parts in the staghorn fern’s life cycle. There is little research on, but a lot of confusion with, staghorn fern species. It has been found that many ferns within the genus Platycerium will superficially resemble one another, and that the number of horn/finger projections will vary depending on how much light and water the plant is receiving. Leave the dead shields on the plant, as they help the plant regulate water!",
        sunlight: 'parsed',
        maintenance: 'medium',
        size: 'medium',
        moisture: 'medium',
        humidity: 'normal',
        expertiseLevel: 'intermediate',
        plantOrigins: 'Southeast Asia, Australia, and Polynesia'
    },
    {
        name: "Mini Succulent Trio", 
        plantImage: "https://i.imgur.com/bsSbrQH.png",
        scientificName: "N/A",
        price: 15, 
        quantityAvail: 10,
        description: "Did you know that not all succulents are related to one another? Succulent is an umbrella term used in the plant world to denote any plant that has adapted to survive in arid sunny conditions. Think: dry desert! Many different species have evolved to have similar drought-surviving adaptations. Some have evolved to be so similar, that they are often confused with one another — like cacti and euphorbias. Adaptations include thickened, waxy leaves, water-storing stems, self-shading mechanisms (such as spines), or an alternative form of photosynthesis (such as C4 or CAM).",
        sunlight: 'direct',
        maintenance: 'low',
        size: 'small',
        moisture: 'low',
        humidity: 'dry',
        expertiseLevel: 'beginner',
        plantOrigins: 'Arid climates and deserts'
    },
    {
        name: "Plastic Plant", 
        plantImage: "https://i.imgur.com/GezwzBF.png",
        scientificName: "Plantanoues plasticus",
        price: 8, 
        quantityAvail: 10,
        description: "This plant is perfect for someone who wants a plant, but doesn't want to do any work AT ALL. Ignore this plant all you want, and it won't be hurt. Go travel the world, come back 5 years later, and this faithful plant will be waiting for you right where you left it. If you feel like it, all you need to do is wipe it clean with a damp cloth once a year.",
        sunlight: 'none',
        maintenance: 'low',
        size: 'large',
        moisture: 'low',
        humidity: 'normal',
        expertiseLevel: 'beginner',
        plantOrigins: 'IKEA'
    }
]

module.exports = plants;