var plants = [
    {
        name: "Charlene Branch1", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'none',
        maintenance: 'low',
        size: 'small',
        moisture: 'low',
        humidity: 'dry',
        expertiseLevel: 'beginner'
    },
    {
        name: "Charlene Branch2", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'none',
        maintenance: 'medium',
        size: 'medium',
        moisture: 'medium',
        humidity: 'normal',
        expertiseLevel: 'intermediate'
    },
    {
        name: "Charlene Branch3", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'none',
        maintenance: 'high',
        size: 'large',
        moisture: 'high',
        humidity: 'humid',
        expertiseLevel: 'expert'
    },
    {
        name: "Charlene Branch4", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'parsed',
        maintenance: 'low',
        size: 'small',
        moisture: 'medium',
        humidity: 'dry',
        expertiseLevel: 'intermediate'
    },
    {
        name: "Charlene Branch5", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'direct',
        maintenance: 'high',
        size: 'large',
        moisture: 'high',
        humidity: 'humid',
        expertiseLevel: 'expert'
    },
    {
        name: "Charlene Branch6", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'parsed',
        maintenance: 'medium',
        size: 'medium',
        moisture: 'medium',
        humidity: 'normal',
        expertiseLevel: 'intermediate'
    },
    {
        name: "Charlene Branch7", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'direct',
        maintenance: 'high',
        size: 'small',
        moisture: 'high',
        humidity: 'dry',
        expertiseLevel: 'beginner'
    },
    {
        name: "Charlene Branch8", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'direct',
        maintenance: 'low',
        size: 'large',
        moisture: 'medium',
        humidity: 'normal',
        expertiseLevel: 'beginner'
    },
    {
        name: "Charlene Branch9", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'none',
        maintenance: 'medium',
        size: 'large',
        moisture: 'low',
        humidity: 'humid',
        expertiseLevel: 'intermediate'
    },
    {
        name: "Charlene Branch10", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'none',
        maintenance: 'low',
        size: 'small',
        moisture: 'low',
        humidity: 'humid',
        expertiseLevel: 'intermediate'
    },
    {
        name: "Charlene Branch11", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'parsed',
        maintenance: 'medium',
        size: 'small',
        moisture: 'low',
        humidity: 'humid',
        expertiseLevel: 'intermediate'
    },
    {
        name: "Charlene Branch12", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'none',
        maintenance: 'low',
        size: 'small',
        moisture: 'low',
        humidity: 'normal',
        expertiseLevel: 'beginner'
    },
    {
        name: "Charlene Branch13", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'parsed',
        maintenance: 'low',
        size: 'medium',
        moisture: 'medium',
        humidity: 'normal',
        expertiseLevel: 'beginner'
    },
    {
        name: "Charlene Branch14", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'direct',
        maintenance: 'low',
        size: 'large',
        moisture: 'high',
        humidity: 'normal',
        expertiseLevel: 'beginner'
    },
    {
        name: "Charlene Branch15", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'none',
        maintenance: 'medium',
        size: 'small',
        moisture: 'high',
        humidity: 'humid',
        expertiseLevel: 'expert'
    },
    {
        name: "Charlene Branch16", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'none',
        maintenance: 'medium',
        size: 'medium',
        moisture: 'low',
        humidity: 'dry',
        expertiseLevel: 'expert'
    },
    {
        name: "Charlene Branch17", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'none',
        maintenance: 'low',
        size: 'small',
        moisture: 'low',
        humidity: 'dry',
        expertiseLevel: 'beginner'
    },
    {
        name: "Charlene Branch18", 
        plantImage: "https://inanyevent.com.au/wp-content/uploads/2018/02/Fig-Leaves-1.jpg",
        scientificName: "Charlenous-Gipulanian-Brancheous",
        price: 10, 
        quantityAvail: 10,
        description: "The best branch you will ever find",
        sunlight: 'parsed',
        maintenance: 'medium',
        size: 'medium',
        moisture: 'medium',
        humidity: 'normal',
        expertiseLevel: 'intermediate'
    }
]

module.exports = plants;